"""AUTO-GENERATED by generate_frozen_reference.py --overwrite (2026-09-21T08:21:03Z).

Frozen, fully expanded cobaya configuration for example2
(source: EXAMPLE_EVALUATE2.yaml resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {
    "As_1e9": 2.1,
    "DES_A1_1": 0.606102,
    "DES_A1_2": -1.51541,
    "DES_A2_1": 0.01,
    "DES_A2_2": -1.5448080290038528,
    "DES_B1_1": 1.72716,
    "DES_B1_2": 1.65168,
    "DES_B1_3": 1.61423,
    "DES_B1_4": 1.92886,
    "DES_B1_5": 2.11633,
    "DES_BTA_1": 0.8154011496506723,
    "DES_DZ_L1": 0.00457604,
    "DES_DZ_L2": 0.000309875,
    "DES_DZ_L3": 0.00855907,
    "DES_DZ_L4": -0.00316269,
    "DES_DZ_L5": -0.0146753,
    "DES_DZ_S1": 0.0414632,
    "DES_DZ_S2": 0.00147332,
    "DES_DZ_S3": 0.0237035,
    "DES_DZ_S4": -0.0773436,
    "DES_M1": 0.0191832,
    "DES_M2": -0.0431752,
    "DES_M3": -0.034961,
    "DES_M4": -0.0158096,
    "H0": 67.32,
    "mnu": 0.06,
    "ns": 0.96605,
    "omegab": 0.04,
    "omegam": 0.3,
    "w": -0.9,
    "w0pwa": -0.9
}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.65
    proposal: 0.4
    latex: 10^9 A_\mathrm{s}
    drop: true
    renames: A
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 5
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.0495
      scale: 0.004
    proposal: 0.004
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.316
      scale: 0.02
    proposal: 0.02
    latex: \Omega_\mathrm{m}
    drop: true
  mnu:
    prior:
      min: 0.06
      max: 0.6
    ref:
      dist: norm
      loc: 0.25
      scale: 0.1
    proposal: 0.05
  w0pwa:
    prior:
      min: -5
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}+w_{a,\mathrm{DE}}
    drop: true
  w:
    prior:
      min: -3
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  DES_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.018
    ref:
      dist: norm
      loc: 0.0
      scale: 0.018
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^1
  DES_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.015
    ref:
      dist: norm
      loc: 0.0
      scale: 0.015
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^2
  DES_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.011
    ref:
      dist: norm
      loc: 0.0
      scale: 0.011
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^3
  DES_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.017
    ref:
      dist: norm
      loc: 0.0
      scale: 0.017
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^4
  DES_M1:
    prior:
      dist: norm
      loc: -0.006
      scale: 0.009
    ref:
      dist: norm
      loc: -0.006
      scale: 0.009
    proposal: 0.004
    latex: m_\mathrm{DES}^1
  DES_M2:
    prior:
      dist: norm
      loc: -0.02
      scale: 0.008
    ref:
      dist: norm
      loc: -0.02
      scale: 0.008
    proposal: 0.004
    latex: m_\mathrm{DES}^2
  DES_M3:
    prior:
      dist: norm
      loc: -0.024
      scale: 0.008
    ref:
      dist: norm
      loc: -0.024
      scale: 0.008
    proposal: 0.004
    latex: m_\mathrm{DES}^3
  DES_M4:
    prior:
      dist: norm
      loc: -0.037
      scale: 0.008
    ref:
      dist: norm
      loc: -0.037
      scale: 0.008
    proposal: 0.003
    latex: m_\mathrm{DES}^4
  DES_A1_1:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: 0.7
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{1-IA,DES}^1
  DES_A1_2:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -1.7
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{1-IA,DES}^2
  DES_A2_1:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -1.36
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{2-IA,DES}^1
  DES_A2_2:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -2.5
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{2-IA,DES}^2
  DES_BTA_1:
    prior:
      min: 0
      max: 2
    ref:
      dist: norm
      loc: 1
      scale: 0.15
    proposal: 0.1
    latex: A_\mathrm{BTA-IA,DES}^1
  DES_DZ_L1:
    prior:
      dist: norm
      loc: 0.006
      scale: 0.004
    ref:
      dist: norm
      loc: 0.006
      scale: 0.004
    proposal: 0.002
    latex: \Delta z_\mathrm{l,DES}^1
  DES_DZ_L2:
    prior:
      dist: norm
      loc: 0.001
      scale: 0.003
    ref:
      dist: norm
      loc: 0.0001
      scale: 0.003
    proposal: 0.001
    latex: \Delta z_\mathrm{l,DES}^2
  DES_DZ_L3:
    prior:
      dist: norm
      loc: 0.004
      scale: 0.003
    ref:
      dist: norm
      loc: 0.0004
      scale: 0.003
    proposal: 0.001
    latex: \Delta z_\mathrm{l,DES}^3
  DES_DZ_L4:
    prior:
      dist: norm
      loc: -0.002
      scale: 0.005
    ref:
      dist: norm
      loc: -0.002
      scale: 0.005
    proposal: 0.002
    latex: \Delta z_\mathrm{l,DES}^4
  DES_DZ_L5:
    prior:
      dist: norm
      loc: -0.007
      scale: 0.01
    ref:
      dist: norm
      loc: -0.007
      scale: 0.01
    proposal: 0.005
    latex: \Delta z_\mathrm{l,DES}^5
  DES_BMAG_1:
    value: 0.63
    latex: b_\mathrm{BMAG-DES}^1
  DES_BMAG_2:
    value: -3.04
    latex: b_\mathrm{BMAG-DES}^2
  DES_BMAG_3:
    value: -1.33
    latex: b_\mathrm{BMAG-DES}^3
  DES_BMAG_4:
    value: 2.5
    latex: b_\mathrm{BMAG-DES}^4
  DES_BMAG_5:
    value: 1.93
    latex: b_\mathrm{BMAG-DES}^5
  DES_PM1:
    latex: PM_\mathrm{DES}^1
    value: 0.0
  DES_PM2:
    latex: PM_\mathrm{DES}^2
    value: 0.0
  DES_PM3:
    latex: PM_\mathrm{DES}^3
    value: 0.0
  DES_PM4:
    latex: PM_\mathrm{DES}^4
    value: 0.0
  DES_PM5:
    latex: PM_\mathrm{DES}^5
    value: 0.0
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
    derived: true
  wa:
    value: 'lambda w0pwa, w: w0pwa - w'
    latex: w_{a,\mathrm{DE}}
    derived: true
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
    derived: true
    renames:
    - ombh2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
    derived: true
    renames:
    - omch2
  omegal:
    latex: \Omega_\Lambda
    derived: true
    renames:
    - omega_de
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
    derived: true
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
    derived: true
  rdrag:
    latex: r_\mathrm{drag}
    derived: true
  yheused:
    latex: Y_P^\mathrm{BBN}
    derived: true
    renames:
    - YHe
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
    derived: true
    renames:
    - omnuh2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  DES_B1_1:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.7
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-DES}^1
  DES_B1_2:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.7
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-DES}^2
  DES_B1_3:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.7
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-DES}^3
  DES_B1_4:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 2.0
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-DES}^4
  DES_B1_5:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 2.0
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-DES}^5
  DES_B2_1:
    value: 0.0
    latex: b_\mathrm{2-DES}^1
  DES_B2_2:
    value: 0.0
    latex: b_\mathrm{2-DES}^2
  DES_B2_3:
    value: 0.0
    latex: b_\mathrm{2-DES}^3
  DES_B2_4:
    value: 0.0
    latex: b_\mathrm{2-DES}^4
  DES_B2_5:
    value: 0.0
    latex: b_\mathrm{2-DES}^5
  DES_B3NL_1:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^1
  DES_B3NL_2:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^2
  DES_B3NL_3:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^3
  DES_B3NL_4:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^4
  DES_B3NL_5:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^5
  DES_BK_1:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^1
  DES_BK_2:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^2
  DES_BK_3:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^3
  DES_BK_4:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^4
  DES_BK_5:
    value: 0.0
    latex: b_\mathrm{BMAG-DES}^5
  DES_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,DES}^3
  DES_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,DES}^4
  DES_A2_3:
    value: 0
    latex: A_\mathrm{2-IA,DES}^3
  DES_A2_4:
    value: 0
    latex: A_\mathrm{2-IA,DES}^4
  DES_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^2
  DES_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^3
  DES_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^4
  DES_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{DES}^1
  DES_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{DES}^2
  DES_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{DES}^3
  DES_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{DES}^4
likelihood:
  des_y3.combo_3x2pt:
    path: ./projects/des_y3/tests/frozen/data
    data_file: des_y3_real.dataset
    accuracyboost: 1.0
    integration_accuracy: 0
    lmax: 50000
    kmax_boltzmann: 5.0
    speed: 1
    non_linear_emul: 2
    external_nz_modeling: 0
    use_emulator: 0
    debug: false
    IA_redshift_evolution: 3
    IA_model: 0
    IA_code: 0
    bias_model:
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    add_baryons_on_dv: false
    which_bsims_add_on_dv: antilles-2
    use_baryon_pca: false
    create_baryon_pca: false
    baryon_pca_select_sims: antilles-2-99/antilles-101-378/antilles-380-400
    filename_baryon_pca: ./projects/lsst_y1/chains/pca.txt
    external_baryon_suppression: false
    print_datavector: false
    print_datavector_file: ./projects/des_y3/chains/theory.modelvector
    type: []
    stop_at_error: false
    version: null
    input_params:
    - H0
    - DES_DZ_S1
    - DES_DZ_S2
    - DES_DZ_S3
    - DES_DZ_S4
    - DES_M1
    - DES_M2
    - DES_M3
    - DES_M4
    - DES_A1_1
    - DES_A1_2
    - DES_A2_1
    - DES_A2_2
    - DES_BTA_1
    - DES_DZ_L1
    - DES_DZ_L2
    - DES_DZ_L3
    - DES_DZ_L4
    - DES_DZ_L5
    - DES_BMAG_1
    - DES_BMAG_2
    - DES_BMAG_3
    - DES_BMAG_4
    - DES_BMAG_5
    - DES_PM1
    - DES_PM2
    - DES_PM3
    - DES_PM4
    - DES_PM5
    - As
    - DES_B1_1
    - DES_B1_2
    - DES_B1_3
    - DES_B1_4
    - DES_B1_5
    - DES_B2_1
    - DES_B2_2
    - DES_B2_3
    - DES_B2_4
    - DES_B2_5
    - DES_B3NL_1
    - DES_B3NL_2
    - DES_B3NL_3
    - DES_B3NL_4
    - DES_B3NL_5
    - DES_BK_1
    - DES_BK_2
    - DES_BK_3
    - DES_BK_4
    - DES_BK_5
    - DES_A1_3
    - DES_A1_4
    - DES_A2_3
    - DES_A2_4
    - DES_BTA_2
    - DES_BTA_3
    - DES_BTA_4
    - DES_BARYON_Q1
    - DES_BARYON_Q2
    - DES_BARYON_Q3
    - DES_BARYON_Q4
    output_params: []
theory:
  camb:
    version: 1.6.7
    path: ./external_modules/code/CAMB
    speed: 0.3
    stop_at_error: false
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 10
      kmax: 5
    ignore_obsolete: false
    use_renames: true
    external_primordial_pk: false
    use_non_linear_ratio: false
    renames:
      omegabh2: ombh2
      omegach2: omch2
      omegal: omega_de
      omegak: omk
      yhe: YHe
      yheused: YHe
      YpBBN: Y_p
      omegan2: omnuh2
    input_params:
    - ns
    - As
    - H0
    - mnu
    - w
    - tau
    - wa
    - omegabh2
    - omegach2
    output_params:
    - omegal
    - sigma8
    - age
    - rdrag
    - yheused
    - omegan2
timing: false
"""
